CREATE TABLE `suites` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `address` varchar(100) NOT NULL,
  `status` enum('交割中','待装修','硬装中','配置中','现房','已下架') NOT NULL,
  `xiaoqu_id` int(10) unsigned DEFAULT NULL,
  `type` varchar(5) NOT NULL,
  `sign_type` varchar(10) DEFAULT NULL,
  `is_month` enum('是','否') NOT NULL DEFAULT '否',
  `city_name` varchar(10) DEFAULT NULL,
  `floor` smallint(5) unsigned DEFAULT NULL,
  `total_floor` smallint(5) unsigned DEFAULT NULL,
  `built_years` smallint(5) unsigned DEFAULT NULL,
  `usable_area` int(10) unsigned DEFAULT NULL COMMENT '套内使用面积',
  `area` smallint(5) unsigned DEFAULT NULL,
  `bedroom_num` tinyint(3) unsigned NOT NULL,
  `toilet_num` tinyint(3) unsigned NOT NULL,
  `public_space_num` tinyint(3) unsigned DEFAULT NULL,
  `kitchen_num` tinyint(3) unsigned DEFAULT NULL,
  `has_lift` enum('有','无') DEFAULT NULL,
  `heating` varchar(20) DEFAULT NULL,
  `hot_water_type` varchar(20) DEFAULT NULL,
  `landlord_id` int(10) unsigned DEFAULT NULL,
  `dealer_id` int(10) unsigned DEFAULT NULL,
  `housekeeper_id` int(10) unsigned DEFAULT NULL,
  `zhuangxiu_designer_id` int(10) DEFAULT NULL,
  `clean_day` smallint(5) unsigned NOT NULL,
  `rent_begin_date` date DEFAULT NULL,
  `rent_end_date` date DEFAULT NULL,
  `zhuangxiu_begin_date` date DEFAULT NULL,
  `zhuangxiu_end_date` date DEFAULT NULL,
  `equip_end_date` date DEFAULT NULL,
  `network_end_date` date DEFAULT NULL,
  `clean_end_date` date DEFAULT NULL,
  `acceptance_date` date DEFAULT NULL,
  `ready_for_rent_date` date DEFAULT NULL,
  `delay_equip_end_date` date DEFAULT NULL,
  `delay_clean_end_date` date DEFAULT NULL,
  `delay_acceptance_date` date DEFAULT NULL,
  `delay_ready_for_rent_date` date DEFAULT NULL,
  `intro` text,
  `images` text,
  `documents` text,
  `bandwidth` int(10) unsigned DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `suites_xiaoqu_id_address_unique` (`xiaoqu_id`,`address`),
  KEY `suites_address_index` (`address`),
  KEY `suites_updated_at_index` (`updated_at`),
  KEY `suites_landlord_id_foreign` (`landlord_id`),
  KEY `suites_dealer_id_foreign` (`dealer_id`),
  KEY `suites_status_index` (`status`),
  KEY `suites_house_keeper_id_index` (`housekeeper_id`),
  KEY `suites_equip_end_date_index` (`equip_end_date`),
  KEY `suites_is_month_index` (`is_month`),
  KEY `suites_city_name_index` (`city_name`)
) ENGINE=InnoDB AUTO_INCREMENT=25766 DEFAULT CHARSET=utf8mb4;

CREATE TABLE `subways` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `city` varchar(10) DEFAULT NULL,
  `name` varchar(20) NOT NULL,
  `lng_lat` varchar(30) DEFAULT NULL,
  `lines` varchar(100) DEFAULT NULL,
  `nearby` varchar(2000) DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `subways_name_index` (`name`)
) ENGINE=InnoDB AUTO_INCREMENT=2315 DEFAULT CHARSET=utf8mb4;

CREATE TABLE `xiaoqus` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(32) NOT NULL,
  `alias` varchar(100) DEFAULT NULL,
  `city` varchar(10) NOT NULL,
  `district` varchar(10) NOT NULL,
  `block` varchar(10) NOT NULL,
  `block_id` int(11) DEFAULT NULL,
  `active` tinyint(4) NOT NULL DEFAULT '1',
  `danke_rent_tag` varchar(8) DEFAULT NULL,
  `subway_id` int(4) DEFAULT NULL,
  `to_subway` int(11) DEFAULT '0' COMMENT '小区到地铁站距离',
  `subway_duration` int(6) DEFAULT NULL COMMENT '到地铁的时间',
  `subway_distance` int(6) DEFAULT NULL COMMENT '到地铁的距离',
  `lng_lat` varchar(32) DEFAULT NULL,
  `longitude` double DEFAULT NULL,
  `latitude` double DEFAULT NULL,
  `type` varchar(12) DEFAULT NULL,
  `traffic_situation` text,
  `intro` text,
  `available_isp_list` varchar(100) DEFAULT NULL,
  `internal_note` text,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `certificate_address` varchar(32) DEFAULT NULL COMMENT '证载地址',
  `is_lock` enum('是','否') NOT NULL DEFAULT '否' COMMENT '是否锁死',
  PRIMARY KEY (`id`),
  KEY `xiaoqus_name_index` (`name`),
  KEY `xiaoqus_station_id_index` (`subway_id`),
  KEY `xiaoqus_block_index` (`block`),
  KEY `xiaoqus_alias_index` (`alias`),
  KEY `xiaoqus_block_id_index` (`block_id`),
  KEY `xiaoqus_longitude_index` (`longitude`),
  KEY `xiaoqus_latitude_index` (`latitude`),
  KEY `xiaoqus_district_index` (`district`),
  KEY `xiaoqus_danke_rent_tag_index` (`danke_rent_tag`),
  KEY `xiaoqus_certificate_address_index` (`certificate_address`)
) ENGINE=InnoDB AUTO_INCREMENT=47539 DEFAULT CHARSET=utf8mb4;

