CREATE TABLE `subscribe` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `city_id` int(11) NOT NULL DEFAULT '0' COMMENT '城市id',
  `city_name` varchar(50)  NOT NULL DEFAULT '' COMMENT '城市名称',
  `uid` int(11) NOT NULL DEFAULT '0' COMMENT '用户id',
  `name` varchar(100)  NOT NULL DEFAULT '' COMMENT '订阅名称',
  `param` varchar(1000)  NOT NULL DEFAULT '' COMMENT '订阅数据串',
  `mkey` varchar(32)  NOT NULL DEFAULT '' COMMENT '订阅唯一key',
  `district` varchar(20)  NOT NULL DEFAULT '' COMMENT '地区',
  `block` varchar(20)  NOT NULL DEFAULT '' COMMENT '商圈',
  `rent_type` varchar(10)  NOT NULL DEFAULT '' COMMENT '租房类型',
  `room_type` varchar(20)  NOT NULL DEFAULT '' COMMENT '房屋类型',
  `min_price` float(10,2) NOT NULL DEFAULT '0.00' COMMENT '最低价格',
  `max_price` float(10,2) NOT NULL DEFAULT '0.00' COMMENT '最高价格',
  `min_area` tinyint(2) NOT NULL DEFAULT '0' COMMENT '最低面积',
  `max_area` tinyint(2) NOT NULL DEFAULT '0' COMMENT '最高面积',
  `status` varchar(10)  NOT NULL DEFAULT '' COMMENT '房屋状态',
  `direction` varchar(50)  NOT NULL DEFAULT '' COMMENT '朝向',
  `feature` varchar(100)  NOT NULL DEFAULT '' COMMENT '房屋特色',
  `isMonth` varchar(10)  NOT NULL DEFAULT '' COMMENT '是否可月租',
  `hasVideo` varchar(10)  NOT NULL DEFAULT '' COMMENT '是否视频看房',
  `heating` varchar(20)  NOT NULL DEFAULT '' COMMENT '是否集中供暖',
  `brand` varchar(10)  NOT NULL DEFAULT '' COMMENT '是否品质公寓',
  `isNearSubway` varchar(10)  NOT NULL DEFAULT '' COMMENT '是否近地铁',
  `hasShower` varchar(10)  NOT NULL DEFAULT '' COMMENT '是否独立淋浴',
  `hasBalcony` varchar(10)  NOT NULL DEFAULT '' COMMENT '是否独立阳台',
  `hasToilet` varchar(10)  NOT NULL DEFAULT '' COMMENT '是否独立卫生间',
  `style` varchar(100)  NOT NULL DEFAULT '' COMMENT '房屋风格',
  `addtime` datetime NOT NULL COMMENT '添加时间',
  `modtime` datetime NOT NULL COMMENT '修改时间',
  PRIMARY KEY (`id`),
  KEY `city_name` (`city_name`),
  KEY `position` (`district`,`block`),
  KEY `rent_type` (`rent_type`),
  KEY `room_type` (`room_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `subscribe_relate` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT COMMENT '关系主键',
  `city_id` int(11) NOT NULL DEFAULT '0' COMMENT '城市id',
  `uid` int(11) NOT NULL DEFAULT '0' COMMENT '用户id',
  `subscribe_id` int(11) NOT NULL DEFAULT '0' COMMENT '订阅id',
  `addtime` datetime NOT NULL COMMENT '添加时间',
  `modtime` datetime NOT NULL COMMENT '修改时间',
  `deleted` enum('N','Y') NOT NULL DEFAULT 'N' COMMENT '删除标识',
  PRIMARY KEY (`id`),
  KEY `index` (`city_id`,`uid`,`subscribe_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='订阅用户表';