`id`  int(10) UNSIGNED NOT NULL AUTO_INCREMENT ,
`code`  varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL ,
`suite_id`  int(10) UNSIGNED NOT NULL ,
`room_number`  varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL ,
`customer_id`  int(10) UNSIGNED NULL DEFAULT NULL ,
`dealer_id`  int(10) UNSIGNED NULL DEFAULT NULL ,
`contract_signed_date`  date NULL DEFAULT NULL ,
`area`  smallint(5) UNSIGNED NULL DEFAULT NULL ,
`price`  int(10) UNSIGNED NULL DEFAULT NULL ,
`month_price`  int(10) UNSIGNED NULL DEFAULT NULL ,
`status`  enum('不可租','可出租','已预定','已出租','已下架','锁定中') CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL ,
`unusable_status`  varchar(12) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL ,
`sold_out_status`  varchar(12) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL ,
`rent_type`  varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL ,
`fire`  enum('是','否') CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '否' ,
`has_error`  tinyint(4) NOT NULL DEFAULT 0 COMMENT '房间是否为问题房源' ,
`city_name`  varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL ,
`face`  enum('东','南','西','北','东南','东北','西南','西北','未知') CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL ,
`available_date`  date NULL DEFAULT NULL ,
`rent_begin_date`  date NULL DEFAULT NULL ,
`rent_end_date`  date NULL DEFAULT NULL ,
`is_separated_room`  enum('是','否') CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL ,
`is_abs`  enum('是','否') CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '否' ,
`has_toilet`  enum('有','无') CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL ,
`has_shower`  enum('有','无') CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL ,
`has_balcony`  enum('有','无') CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL ,
`has_tv`  enum('有','无') CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL ,
`has_terrace`  enum('有','无') CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL ,
`has_storeroom`  enum('有','无') CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL ,
`allow_quarterly`  enum('否','是') CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL ,
`living_area`  tinyint(3) UNSIGNED NULL DEFAULT NULL ,
`toilet_area`  tinyint(3) UNSIGNED NULL DEFAULT NULL ,
`balcony_area`  tinyint(3) UNSIGNED NULL DEFAULT NULL ,
`terrace_area`  tinyint(3) UNSIGNED NULL DEFAULT NULL ,
`storeroom_area`  tinyint(3) UNSIGNED NULL DEFAULT NULL ,
`has_image`  enum('有','无') CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT '无' ,
`version`  varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL ,
`style`  varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL ,
`lighting`  enum('私有采光','非私有采光','无采光') CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL ,
`is_small_window`  enum('是','否') CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL ,
`has_curtains`  enum('是','否','特殊窗户-需要供应商测量') CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL ,
`is_rent_furniture`  enum('否','是') CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL ,
`shape`  varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL ,
`shape_note`  varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL ,
`address_text`  varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL ,
`search_text`  varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL ,
`disable_expire_date`  date NULL DEFAULT NULL ,
`disable_by`  int(10) UNSIGNED NULL DEFAULT NULL ,
`disable_note`  varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL ,
`image_number`  tinyint(3) UNSIGNED NOT NULL DEFAULT 0 ,
`images`  text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL ,
`documents`  text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL ,
`advantages`  varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL ,
`deleted_at`  datetime NULL DEFAULT NULL ,
`auto_note`  text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL ,
`auto_change_date`  date NULL DEFAULT NULL ,
`auto_change_end_date`  date NULL DEFAULT NULL ,
`auto_status`  varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL ,
`created_at`  datetime NOT NULL ,
`updated_at`  datetime NOT NULL ,
`is_photographer_uploaded`  enum('是','否') CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL ,
`room_length`  double NULL DEFAULT NULL COMMENT '长度' ,
`room_width`  double NULL DEFAULT NULL COMMENT '宽度' ,
`room_height`  double NULL DEFAULT NULL ,
`room_type`  varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '类型' ,
`has_cloakroom`  varchar(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '是否有储物间/衣帽间' ,
`has_bay_window`  varchar(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '是否有飘窗' ,
`has_window`  varchar(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '是否有窗' ,
`is_wired_loft`  varchar(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '是否有大斜顶' ,
`is_wired_long_and_thin`  varchar(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '是否狭长型' ,
`is_bad_lighting`  varchar(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '采光差' ,
`is_private_window`  varchar(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '独立窗户' ,
`is_near_street`  varchar(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '靠近大街' ,
`cleaning_tools_tag`  varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL ,
`door_tag`  varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL ,
`floor_tag`  varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL ,
`kitchen_ware_tag`  varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL ,
`is_house_state_readonly`  varchar(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '房态是否锁定' ,
`is_price_readonly`  varchar(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '价格是否锁定' ,
`is_room_info_readonly`  varchar(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '是否小窗户' ,
`is_rough_room`  varchar(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '是否毛坯' ,
`roof_tag`  varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL ,
`wall_floor_tag`  varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL ,
`wall_tag`  varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL ,
`window_tag`  varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL ,
`others_tear_down_tag`  varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL ,
`has_private_kitchen`  varchar(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '是否有独立厨房' ,
`has_toilet_in_bathroom`  varchar(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '独卫是否有马桶' ,
`toilet_type`  varchar(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '卫生间类型：公卫、独卫、房间外独卫、房间内独卫' ,
`temp_price_yuan`  int(11) NOT NULL DEFAULT 0 COMMENT '模型计算机' ,
`revalue_price_yuan`  int(11) NOT NULL DEFAULT 0 COMMENT '收到修正价' ,
`plan_id`  int(11) NULL DEFAULT NULL COMMENT '改造方案ID' ,
`house_id`  int(10) UNSIGNED NULL DEFAULT NULL COMMENT 'BI门牌ID' ,
`bi_room_id`  int(10) UNSIGNED NULL DEFAULT NULL ,
`toilet_tag`  varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL ,
`has_video`  varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT '无' COMMENT '房间是否上传视频' ,
`videos`  varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT 'null' COMMENT '视频地址' ,
`video_rack_status`  enum('上架','下架') CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '下架' COMMENT '视频上架下架' ,
`bedroom_type`  varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL ,
`is_verify`  enum('是','否') CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '否' ,
`is_wall_white`  varchar(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '墙面是否白漆' ,
`is_leave_furniture`  varchar(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '是否有留用床/衣柜' ,
`bay_window_area`  decimal(8,2) NULL DEFAULT 0.00 COMMENT '飘窗面积' ,
`isz_house_id`  int(11) NOT NULL COMMENT '是否是爱上租' ,