[
    {
        "listData":[
            {
                "iconCityCode":"1",
                "iconCityName":"北京市",
                "iconName":"合租",
                "iconPic":"public-20180815-UCyGGqa78xK5r4buX4D",
                "iconUrl":"dankegongyu://app/customer/room/list?rent_type=2",
                "versionEnd":"2.0.0",
                "versionStart":"1.8.0"
            },
            {
                "iconCityCode":"1",
                "iconCityName":"北京市",
                "iconName":"整租",
                "iconPic":"public-20180815-z5KaiLDTLC4qaK4pvRu",
                "iconUrl":"dankegongyu://app/customer/room/list?rent_type=1",
                "versionEnd":"2.0.0",
                "versionStart":"1.8.0"
            },
            {
                "iconCityCode":"1",
                "iconCityName":"北京市",
                "iconName":"地图找房",
                "iconPic":"public-20180815-0440pFmF237ABXxhPQf",
                "iconUrl":"dankegongyu://app/customer/map/room",
                "versionEnd":"2.0.0",
                "versionStart":"1.8.0"
            },
            {
                "iconCityCode":"1",
                "iconCityName":"北京市",
                "iconName":"房屋委托",
                "iconPic":"public-20180815-SfLO7CLgb2u4XZxnqFZ",
                "iconUrl":"https://www.dankegongyu.com/about/mobile_yezhu.html",
                "versionEnd":"2.0.0",
                "versionStart":"1.8.0"
            }
        ],
        "modelImgUrl":"",
        "modelType":1,
        "modelUrl":"",
        "subTitle":"1",
        "title":"1"
    },
    {
        "listData":[
            {
                "linkUrl":"http://www.dankegongyu.com/zhuanti/trade?city=bj&trade=by",
                "name":"北苑",
                "picUrl":"public-20171229-4PJ0QQkDYiUaCeFxKKv",
                "seqence":1
            },
            {
                "linkUrl":"http://www.dankegongyu.com/zhuanti/trade?city=bj&trade=hlg",
                "name":"欢乐谷",
                "picUrl":"public-20171229-EOB25qhr9M8t3BqBT42",
                "seqence":2
            },
            {
                "linkUrl":"http://www.dankegongyu.com/zhuanti/trade?city=bj&trade=lshq",
                "name":"立水桥",
                "picUrl":"public-20171229-bc5hbYXJIS72pEs3Z4c",
                "seqence":3
            },
            {
                "linkUrl":"http://www.dankegongyu.com/zhuanti/trade?city=bj&trade=shd",
                "name":"上地",
                "picUrl":"public-20171229-sw4wuuVj6S4MII4DVXR",
                "seqence":4
            },
            {
                "linkUrl":"http://www.dankegongyu.com/zhuanti/trade?city=bj&trade=shlzh",
                "name":"石榴庄",
                "picUrl":"public-20171229-8SAYf8AAvHlx32cn3w7",
                "seqence":5
            },
            {
                "linkUrl":"http://www.dankegongyu.com/zhuanti/trade?city=bj&trade=tty",
                "name":"天通苑",
                "picUrl":"public-20171229-AQ694NnUrx57lYidhPQ",
                "seqence":6
            }
        ],
        "modelImgUrl":"",
        "modelType":2,
        "modelUrl":"",
        "subTitle":"找寻不同的风景",
        "title":"我们都住在这里"
    },
    {
        "bulletScreenColor":"#19c8cc",
        "description":"只为不愿将就的你",
        "leftSubtitleColor":"#48d8c2",
        "listData":[
            {
                "bulletScreenContent":"喜欢这种工业设计风",
                "profilePhoto":"public-20180507-EOGnfOFbdv3iKvXDoZe"
            },
            {
                "bulletScreenContent":"温馨的小屋",
                "profilePhoto":"public-20180507-IbYDWmNQ24lpWkUiz24"
            },
            {
                "bulletScreenContent":"这价格一点都不亏",
                "profilePhoto":"public-20180507-6HApzzTrF0zMPkJCMMA"
            },
            {
                "bulletScreenContent":"喜欢那个枕头哈哈",
                "profilePhoto":"public-20180507-md8js9vPKh7tKnCIBZT"
            },
            {
                "bulletScreenContent":"仙女的房间!",
                "profilePhoto":"public-20180507-dNgWZwd2JhMBYJlTEF6"
            },
            {
                "bulletScreenContent":"性价比挺高的",
                "profilePhoto":"public-20180505-R4ZPIz2F7fcbCK1YAtD"
            },
            {
                "bulletScreenContent":"蛋壳快来成都呀",
                "profilePhoto":"public-20180505-ZGwsRkXzJ6ifDvIVxzH"
            },
            {
                "bulletScreenContent":"好喜欢这装修风格",
                "profilePhoto":"public-20180505-MjPFZhfktoUGsTCVbIk"
            },
            {
                "bulletScreenContent":"好的房子值得好租客",
                "profilePhoto":"public-20180505-fKl583rMikbiZJS2hRr"
            },
            {
                "bulletScreenContent":"家电都是品牌货",
                "profilePhoto":"public-20180505-eQ8DMkflmM0VkQMytkO"
            },
            {
                "bulletScreenContent":"维修小哥哥很及时",
                "profilePhoto":"public-20180505-DG54j5RrxMmmOQDiBvv"
            },
            {
                "bulletScreenContent":"给保洁阿姨满分",
                "profilePhoto":"public-20180505-Vyy6S8rgiijiFOEjKNJ"
            },
            {
                "bulletScreenContent":"家里再也不冷清",
                "profilePhoto":"public-20180505-0TmitxEwlIEiOgNHJa1"
            },
            {
                "bulletScreenContent":"不用自己捣鼓装修了！",
                "profilePhoto":"public-20180505-HYUQnSu0moeke9VlLWF"
            },
            {
                "bulletScreenContent":"精致的猪猪生活",
                "profilePhoto":"public-20180505-7WuGlU31KJruD65tKJ2"
            },
            {
                "bulletScreenContent":"有了家的感觉",
                "profilePhoto":"public-20180505-bRv6FDoxF9n5cA1xl7b"
            },
            {
                "bulletScreenContent":"偷偷赞一个我室友",
                "profilePhoto":"public-20180505-fyXMnVA0c8crlpPRHEF"
            }
        ],
        "modelImgUrl":"public-20180726-pAYfwKpLIBadJVsCoNT",
        "modelType":3,
        "modelUrl":"dankegongyu://app/customer/room/list?rent_type=2",
        "rightSubtitleColor":"#3fc0c5",
        "subTitle":"高品质合租公寓1",
        "tags":[
            "MUJI风",
            "工业风"
        ],
        "title":"蛋壳合租"
    },
    {
        "bulletScreenColor":"#f67765",
        "description":"给你空间自主权",
        "leftSubtitleColor":"#f88d7e",
        "listData":[
            {
                "bulletScreenContent":"现代简约冷淡风",
                "profilePhoto":"public-20180507-gF24QuDWR9J7xSsgOMe"
            },
            {
                "bulletScreenContent":"蛋壳公寓了解一下",
                "profilePhoto":"public-20180507-3Lf5U8HCxOXOpBPdHNA"
            },
            {
                "bulletScreenContent":"审美太好了哭哭",
                "profilePhoto":"public-20180507-V1q3WNTj9JQLlsB8uwH"
            },
            {
                "bulletScreenContent":"这很有逼格",
                "profilePhoto":"public-20180507-yif2TqtL3sF26azFBaP"
            },
            {
                "bulletScreenContent":"我在昆明等蛋壳",
                "profilePhoto":"public-20180507-lI9cnodTMz4nkrzlIXz"
            },
            {
                "bulletScreenContent":"想开party",
                "profilePhoto":"public-20180507-fVhKTfkhZwOmWc7FJ8H"
            },
            {
                "bulletScreenContent":"很佩服这摆设",
                "profilePhoto":"public-20180505-wF3N405GSkEdaOtvJ1r"
            },
            {
                "bulletScreenContent":"格局不错",
                "profilePhoto":"public-20180505-dZe0xj1QUB3iEmpsGTR"
            },
            {
                "bulletScreenContent":"真的好有生活感啊",
                "profilePhoto":"public-20180505-QsxHtrabLxMXtlhYCV7"
            },
            {
                "bulletScreenContent":"想象中的房子！",
                "profilePhoto":"public-20180505-9Inp9Mt4CHa6zWI6gT6"
            },
            {
                "bulletScreenContent":"不用顾忌室友~",
                "profilePhoto":"public-20180505-zZB8IbCkcxxDidNZOi5"
            },
            {
                "bulletScreenContent":"我很喜欢这个梳妆台",
                "profilePhoto":"public-20180505-XWDgcUS2VBaqL2ik3f2"
            },
            {
                "bulletScreenContent":"房间品质赞一个",
                "profilePhoto":"public-20180505-7KVINd099jGuMRh1AmD"
            },
            {
                "bulletScreenContent":"柜子设计的贴心",
                "profilePhoto":"public-20180505-nXlHU1spYdOqY3koeqK"
            },
            {
                "bulletScreenContent":"洗澡不用关门了嘻嘻",
                "profilePhoto":"public-20180505-Pacxjnh9hNsmZ9JkNhx"
            },
            {
                "bulletScreenContent":"开音响练歌~",
                "profilePhoto":"public-20180505-kXR3g2M6RYCrUDDmupK"
            },
            {
                "bulletScreenContent":"住的很自由",
                "profilePhoto":"public-20180505-enUQ7kllvBdvTnAagWy"
            },
            {
                "bulletScreenContent":"一个人住很安静",
                "profilePhoto":"public-20180505-NdoBU1qjTraywCO1k7Y"
            }
        ],
        "modelImgUrl":"public-20180726-KgmV4EtJvcHjZ7Efsex",
        "modelType":6,
        "modelUrl":"dankegongyu://app/customer/room/list?rent_type=1",
        "rightSubtitleColor":"#f57563",
        "subTitle":"真实业主房源1",
        "tags":[
            "随意租",
            "自由住"
        ],
        "title":"蛋壳整租"
    },
    {
        "bulletScreenColor":"#19c8cc",
        "description":"短租虽短暂也美好",
        "leftSubtitleColor":"#24e7c9",
        "listData":[
            {
                "bulletScreenContent":"完美的设计！",
                "profilePhoto":"public-20180505-3xaFJ2yfnfSTEvQ8im1"
            },
            {
                "bulletScreenContent":"租房终于上品质了",
                "profilePhoto":"public-20180505-fz8wy0yFFlxQEp8iAcC"
            },
            {
                "bulletScreenContent":"让人放心",
                "profilePhoto":"public-20180505-alw1tu8uIk4kDFixaEo"
            },
            {
                "bulletScreenContent":"超级好的房间",
                "profilePhoto":"public-20180505-cFaeGGW8rZLu2DUWqFP"
            },
            {
                "bulletScreenContent":"表白维修小哥哥",
                "profilePhoto":"public-20180505-Zi1LsL8jzTqPkXHN0v0"
            },
            {
                "bulletScreenContent":"哇很赞",
                "profilePhoto":"public-20180505-QnfdZDKjMzzPQGqs0tM"
            },
            {
                "bulletScreenContent":"短租也要住的精致",
                "profilePhoto":"public-20180505-yI6G4XXkmG1XkSRanl8"
            },
            {
                "bulletScreenContent":"在北京只待一个月",
                "profilePhoto":"public-20180505-3znl8vzs8bqtQuRLHrA"
            },
            {
                "bulletScreenContent":"方便了我短租",
                "profilePhoto":"public-20180505-N9OrYnKVXFIVB0rQGuV"
            },
            {
                "bulletScreenContent":"月租很便宜",
                "profilePhoto":"public-20180505-5a2hDUC9ncSZmsooq5j"
            },
            {
                "bulletScreenContent":"租期自由不尴尬",
                "profilePhoto":"public-20180505-tIGLcX5yTtBiBlTEGWn"
            },
            {
                "bulletScreenContent":"月租月轻松",
                "profilePhoto":"public-20180505-NwrUGFamA1m9ZMz358p"
            },
            {
                "bulletScreenContent":"有了家的感觉",
                "profilePhoto":"public-20180505-DJudnzS6G1GTrVLsC0u"
            }
        ],
        "modelImgUrl":"public-20180726-7VfWB0LoFabBbIgYSOr",
        "modelType":7,
        "modelUrl":"dankegongyu://app/customer/room/list?rent_type=3",
        "rightSubtitleColor":"#46e9a3",
        "subTitle":"月租月轻松1",
        "tags":[
            "租期自选",
            "付款灵活"
        ],
        "title":"蛋壳月租"
    },
    {
        "listData":[

        ],
        "modelImgUrl":"",
        "modelType":12,
        "modelUrl":"",
        "subTitle":"1",
        "title":"租客活动"
    },
    {
        "listData":[
            {
                "linkUrl":"https://www.dankegongyu.com/zhuanti/story?storyID=8",
                "picUrl":"public-20180621-1pzbBzrSKyBcDlQz2ks",
                "seqence":1,
                "storySubTitle":"为了租客睡个安稳觉，我一定要当天帮租客处理好事情。",
                "storyTitle":"风雨无阻，只怕服务不到位"
            },
            {
                "linkUrl":"https://www.dankegongyu.com/zhuanti/story?storyID=7",
                "picUrl":"public-20180621-5VdAeQRoSVZJpBy6JNI",
                "seqence":2,
                "storySubTitle":"这位师傅从事维修工作十几年，一直都是这么认真负责、细心、为客人着想。",
                "storyTitle":"35度的太阳也晒不退服务的心"
            },
            {
                "linkUrl":"https://www.dankegongyu.com/zhuanti/story?storyID=6",
                "picUrl":"public-20180621-SJubLZwVgyA8kp0gZgs",
                "seqence":3,
                "storySubTitle":"“更快更好地解决问题，租户才会更信任你，更认可你。”",
                "storyTitle":"将心比心，急人所急"
            }
        ],
        "modelImgUrl":"public-20180205-tGvc6pL4csAiTiL0191",
        "modelType":4,
        "modelUrl":"",
        "subTitle":"听他们的故事",
        "title":"蛋壳故事"
    },
    {
        "listData":[
            {
                "iconName":"客服咨询",
                "linkUrl":"http://www.dankegongyu.com/api-page/daily-problems",
                "picUrl":"public-20171228-RNPYStJYliFtJxV9F39"
            },
            {
                "iconName":"在线报修",
                "linkUrl":"dankegongyu://app/customer/repair/list",
                "picUrl":"public-20171228-1d9eBXxcXYmpeT1UxNg"
            }
        ],
        "modelImgUrl":"",
        "modelType":5,
        "modelUrl":"",
        "subTitle":"专心陪伴 一心守护",
        "title":"生活服务"
    },
    {
        "listData":[
            {
                "advantageImg":"public-20180505-W5kGRMQmgDW20qnfSna",
                "advantageName":"高档家居",
                "checkedLogoImg":"public-20180505-DT2ZZ2rimfMWOOT6tYf",
                "logoImg":"public-20180505-BSXSHmhJ4MhBEUihTZy",
                "seqence":1
            },
            {
                "advantageImg":"public-20180505-mHLH1BQCcOniVt0hNXm",
                "advantageName":"极速WIFI",
                "checkedLogoImg":"public-20180505-3DaVgGCFkTclhA2cEsV",
                "logoImg":"public-20180505-wyEpKocp2x6aOrMfx7A",
                "seqence":2
            },
            {
                "advantageImg":"public-20180505-AMA1I1JMSybrZFLjYCI",
                "advantageName":"双周保洁",
                "checkedLogoImg":"public-20180505-NyCs7s9yNgtAnZHqqnE",
                "logoImg":"public-20180505-7YqYkZcZ7HmnF2k8f7D",
                "seqence":3
            },
            {
                "advantageImg":"public-20180505-kppiFZuWFIGRquv7zAd",
                "advantageName":"专业维修",
                "checkedLogoImg":"public-20180505-eNlow9PjMJ7uWJCcj0N",
                "logoImg":"public-20180505-2alkCHxW5odStHFyz7b",
                "seqence":4
            },
            {
                "advantageImg":"public-20180505-k5XxEbI0g8sSzTdTf89",
                "advantageName":"私人管家",
                "checkedLogoImg":"public-20180505-XxmSoN0zdUOb0DJqml7",
                "logoImg":"public-20180505-47dUsKsH80hGIBI8SrI",
                "seqence":5
            }
        ],
        "modelImgUrl":"",
        "modelType":11,
        "modelUrl":"",
        "subTitle":"蛋壳优势",
        "title":"蛋壳优势"
    },
    {
        "listData":[
            {
                "iconCityCode":"1",
                "iconCityName":"北京市",
                "iconName":"🌹立即预约 最高省2000",
                "iconUrl":"dankegongyu://app/customer/room/list?search_text=活动"
            },
            {
                "iconCityCode":"1",
                "iconCityName":"北京市",
                "iconName":"西二旗",
                "iconUrl":"dankegongyu://app/customer/room/list?search_text=西二旗"
            },
            {
                "iconCityCode":"1",
                "iconCityName":"北京市",
                "iconName":"回龙观",
                "iconUrl":"dankegongyu://app/customer/room/list?search_text=回龙观"
            },
            {
                "iconCityCode":"1",
                "iconCityName":"北京市",
                "iconName":"后厂村",
                "iconUrl":"dankegongyu://app/customer/room/list?search_text=后厂村&status=现房-配置中&orders=price_asc"
            },
            {
                "iconCityCode":"1",
                "iconCityName":"北京市",
                "iconName":"天通苑",
                "iconUrl":"dankegongyu://app/customer/room/list?search_text=天通苑"
            },
            {
                "iconCityCode":"1",
                "iconCityName":"北京市",
                "iconName":"望京",
                "iconUrl":"dankegongyu://app/customer/room/list?search_text=望京"
            },
            {
                "iconCityCode":"1",
                "iconCityName":"北京市",
                "iconName":"青年路",
                "iconUrl":"dankegongyu://app/customer/room/list?search_text=青年路"
            },
            {
                "iconCityCode":"1",
                "iconCityName":"北京市",
                "iconName":"常营",
                "iconUrl":"dankegongyu://app/customer/room/list?search_text=常营"
            }
        ],
        "modelImgUrl":"",
        "modelType":13,
        "modelUrl":"",
        "subTitle":"热词搜索",
        "title":"热词搜索"
    }
]

